### ISSUE TITLE
SIGSEGV when compiling with avx2 and GCC

### ISSUE THREAD

**Issue by zaxster** [blegal/Fast_LDPC_decoder_for_x86#1]
Hi, I've succesfully compiled your software using GCC with -mavx2, but when I run the program with -avx I get a SIGSEGV.

The issue seems to be related to unaligned load and store inside transpose_avc.cpp and CDecoder_NMS_fixed_AVX.cpp

Changing `_mm256_load` with `_mm256_loadu` and _store with _storeu everything works as expected.

Thanks, regards

**Comment by blegal** [comment]
You are right. I suppose that you are using a Linux platform. For an obvious reason
in some case memory allocated in decoders are not memory aligned and it produced
SIGSEGV.

One way to solve the issue is to change _mm256_load with _mm256_loadu, the other
solution is to change the memory allocation using the posix API to have aligned memory.

Thanks, regards

Bertrand

**Comment by zaxster** [comment]
Yes I'm using Linux. 
I've changed "new" with "posix_memalign" and everything is working fine.
