### ISSUE TITLE
app crashes at uchar_transpose_avx:68

### ISSUE THREAD

**Issue by pramodkirchki** [blegal/Fast_LDPC_decoder_for_x86#3]
Hi Bertrand,
    I am compiling and running on a machine which supports avx2 instruction set. I am compiling with gcc 9.2.0 and the app crashes at uchar_transpose_avx line 68. Please find the backtrace below.

```
Core was generated by `./FastLdpc -fixed -avx -NMS 29 -iter 20 -NMS 29 -fer 10000000 -timer 10 -thread 1'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055bd59f14794 in _mm256_unpacklo_epi8(long long __vector(4), long long __vector(4)) (__B=..., __A=...)
    at c:\sandbox\p9\repo\prg_util_toolset\gcc\pu-sdk-mingw-w64-15.1.0\sysroots\x86_64-pubspsdk-mingw32\usr\lib\x86_64-pubsp-linux\gcc\x86_64-pubsp-linux\9.2.0\include/avx2intrin.h:887
#1  uchar_transpose_avx(long long __vector(4)*, long long __vector(4)*, int) (src=<optimized out>, dst=<optimized out>, n=n@entry=576) at ../src/CTools/transpose_avx.cpp:68
#2  0x000055bd59f10276 in CDecoder_NMS_fixed_AVX::decode_8bits (this=0x55bd5a4155c0, Intrinsic_fix=<optimized out>, Rprime_fix=0x55bd5a365b60 "", nombre_iterations=20)
    at ../src/CDecoder/NMS/CDecoder_NMS_fixed_AVX.cpp:134
#3  0x000055bd59f0c55f in main (argc=<optimized out>, argv=<optimized out>) at ../src/main_p.cpp:486
```

The same app with -sse flag seems to work fine. I am sure that the processor I am using supports avx2 instruction set. The 256 bits loads from lines 51-66 seems to work fine. Do you think I have to enable some more flags?

Thanks,
Pramod

**Comment by blegal** [comment]
Dear Pramod,

This is a very old source code you are try to use ;-) It was evaluated many times and normally works fine on many host configurations however, it is not perfect if you are trying to use it with custom LDPC matrices. 

I did not manage clearly some transpose use cases e.g. matrices that are not %32 for AVX2 implementation and %16 for SSE4 parallelization.

Your issue came comes from this. An another possibility is that the GCC does not well manage memory alignement. You can try to change

#define LOAD_SIMD_FX    _mm256_load_si256
#define STORE_SIMD_FX   _mm256_store_si256

to

#define LOAD_SIMD_FX    _mm256_loadu_si256
#define STORE_SIMD_FX   _mm256_storeu_si256

If your are interested with high throughput and very low latency LDPC decoding, we release commercial version of this code (new parallelization scheme) for 5G, DVB-Sx, CCSDS standards. Do not hesitate to contact me if you want more information on expected performance levels.

For later communication, please use <bertrand.legal AT bordeaux-inp.fr>.

Have a nice day,

Bertrand

**Comment by pramodkirchki** [comment]
Hi Bertrand,
   Thanks for the feedback. The crash was solved with aligned data.

Cheers,
Pramod
